"""
Generate LaTeX table of Frobenius traces for the Prym threefold Q.

Method: count #X(F_p) on the regular S_4-closure via
  #X(F_p) = 24 * #{completely split unramified y} + 12*(2+c_roots) + 6,
then extract a_1(Q) from
  a_1(X) = a_1(X_A) + 2*a_1(E_res) + 3*a_1(E) + 3*a_1(Q).

Weierstrass models (verified against LMFDB):
  E_{37a1}: y^2 + y = x^3 - x
  E_res (1147.b1 = Cremona 1147a1): y^2 + y = x^3 - x^2 - 9x + 9
  X_A: w^2 = -y(y-1)(256y^3 + 411y^2 + 165y + 32)
"""
import math
import os

def is_prime(n):
    if n < 2: return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0: return False
    return True

def legendre(a, p):
    if a % p == 0: return 0
    return 1 if pow(a % p, (p-1)//2, p) == 1 else -1

def count_E37(p):
    count = 0
    for x in range(p):
        rhs = (4*pow(x,3,p) - 4*x + 1) % p
        leg = legendre(rhs, p)
        if leg == 0: count += 1
        elif leg == 1: count += 2
    return count + 1

def count_Eres(p):
    count = 0
    for x in range(p):
        rhs = (4*pow(x,3,p) - 4*pow(x,2,p) - 36*x + 37) % p
        leg = legendre(rhs, p)
        if leg == 0: count += 1
        elif leg == 1: count += 2
    return count + 1

def count_XA(p):
    count = 0
    for y in range(p):
        fval = (-y * (y-1) * (256*pow(y,3,p) + 411*pow(y,2,p) + 165*y + 32)) % p
        leg = legendre(fval, p)
        if leg == 0: count += 1
        elif leg == 1: count += 2
    return count + 1

def count_quartic_roots(p, y_val):
    a2 = (-(2*y_val + 1)) % p
    a0 = (y_val * (y_val + 1)) % p
    return sum(1 for l in range(p)
               if (pow(l,4,p) - pow(l,3,p) + a2*pow(l,2,p) + l + a0) % p == 0)

bad_primes = {2, 3, 31, 37}
primes = [p for p in range(5, 120) if is_prime(p) and p not in bad_primes]

results = []
for idx, p in enumerate(primes):
    a1_XA = p + 1 - count_XA(p)
    a1_Eres = p + 1 - count_Eres(p)
    a1_E37 = p + 1 - count_E37(p)

    c_roots = sum(1 for y in range(p)
                  if (256*pow(y,3,p) + 411*pow(y,2,p) + 165*y + 32) % p == 0)

    n_split = 0
    for y in range(p):
        if y == 0 or y == 1: continue
        if (256*pow(y,3,p) + 411*pow(y,2,p) + 165*y + 32) % p == 0: continue
        if count_quartic_roots(p, y) == 4:
            n_split += 1

    total = 24 * n_split + 12 * (2 + c_roots) + 6
    a1_X = p + 1 - total
    rhs = a1_XA + 2*a1_Eres + 3*a1_E37
    diff = a1_X - rhs
    assert diff % 3 == 0, f"p={p}: diff={diff} not divisible by 3"
    a1_Q = diff // 3
    weil_bound = 6 * math.sqrt(p)
    assert abs(a1_Q) <= weil_bound, f"p={p}: |a1(Q)|={abs(a1_Q)} > {weil_bound:.1f}"

    results.append((p, a1_XA, a1_Eres, a1_E37, a1_Q))

    if (idx + 1) % 10 == 0:
        print(f"  progress: {idx+1}/{len(primes)} primes computed")

# Select subset for table (first 15 primes for readability)
table_primes = results[:15]

outdir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                      "sections", "generated") if False else \
         os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "sections", "generated")
os.makedirs(outdir, exist_ok=True)

outpath = os.path.join(outdir, "prym_traces_table.tex")
with open(outpath, "w") as f:
    f.write("% Auto-generated by scripts/generate_Q_traces_table.py\n")
    f.write(r"\begin{tabular}{r|rrrr}" + "\n")
    f.write(r"$p$ & $a_1(\Jac(X_A))$ & $a_1(E_{\mathrm{res}})$ & $a_1(E)$ & $a_1(Q)$ \\ \hline" + "\n")
    for p, a1_XA, a1_Eres, a1_E37, a1_Q in table_primes:
        f.write(f"${p}$ & ${a1_XA}$ & ${a1_Eres}$ & ${a1_E37}$ & ${a1_Q}$ \\\\\n")
    f.write(r"\end{tabular}" + "\n")

print(f"\nTable written to {outpath}")
print(f"Computed {len(results)} primes, all passing Weil bound and divisibility checks.")
print(f"\nFirst 15 a_1(Q) values: {[r[4] for r in results[:15]]}")
